### ISSUE TITLE
Integration with ethernet shield

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jprodgers/LoLshield#24]
```
This version of charlieplexing.cpp uses analog pins instead of digital 8-13 to 
allow the use of ethernet shield.


```

Original issue reported on code.google.com by `max....@gmail.com` on 3 May 2012 at 10:35

Attachments:
* [Charliplexing.cpp](https://storage.googleapis.com/google-code-attachments/lolshield/issue-24/comment-0/Charliplexing.cpp)

**Comment by jprodgers** [comment]
Closing this, as it's not an issue with the official hardware or library.
